/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu' in SOPC Builder design 'nios'
 * SOPC Builder design path: ../../nios.sopcinfo
 *
 * Generated: Sat Jun 20 05:10:26 CST 2026
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_qsys"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00040820
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x13
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x13
#define ALT_CPU_NAME "cpu"
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00040820
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x13
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x13
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_QSYS


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV E"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x41188
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x41188
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x41188
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "nios"


/*
 * hal configuration
 *
 */

#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x41188
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x20000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "nios_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 131072
#define ONCHIP_MEMORY_SPAN 131072
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * pio_in_eep_sda_in configuration
 *
 */

#define ALT_MODULE_CLASS_pio_in_eep_sda_in altera_avalon_pio
#define PIO_IN_EEP_SDA_IN_BASE 0x41060
#define PIO_IN_EEP_SDA_IN_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_IN_EEP_SDA_IN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_IN_EEP_SDA_IN_CAPTURE 0
#define PIO_IN_EEP_SDA_IN_DATA_WIDTH 1
#define PIO_IN_EEP_SDA_IN_DO_TEST_BENCH_WIRING 0
#define PIO_IN_EEP_SDA_IN_DRIVEN_SIM_VALUE 0
#define PIO_IN_EEP_SDA_IN_EDGE_TYPE "NONE"
#define PIO_IN_EEP_SDA_IN_FREQ 50000000
#define PIO_IN_EEP_SDA_IN_HAS_IN 1
#define PIO_IN_EEP_SDA_IN_HAS_OUT 0
#define PIO_IN_EEP_SDA_IN_HAS_TRI 0
#define PIO_IN_EEP_SDA_IN_IRQ -1
#define PIO_IN_EEP_SDA_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_IN_EEP_SDA_IN_IRQ_TYPE "NONE"
#define PIO_IN_EEP_SDA_IN_NAME "/dev/pio_in_eep_sda_in"
#define PIO_IN_EEP_SDA_IN_RESET_VALUE 0
#define PIO_IN_EEP_SDA_IN_SPAN 16
#define PIO_IN_EEP_SDA_IN_TYPE "altera_avalon_pio"


/*
 * pio_in_key configuration
 *
 */

#define ALT_MODULE_CLASS_pio_in_key altera_avalon_pio
#define PIO_IN_KEY_BASE 0x41160
#define PIO_IN_KEY_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_IN_KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_IN_KEY_CAPTURE 0
#define PIO_IN_KEY_DATA_WIDTH 4
#define PIO_IN_KEY_DO_TEST_BENCH_WIRING 0
#define PIO_IN_KEY_DRIVEN_SIM_VALUE 0
#define PIO_IN_KEY_EDGE_TYPE "NONE"
#define PIO_IN_KEY_FREQ 50000000
#define PIO_IN_KEY_HAS_IN 1
#define PIO_IN_KEY_HAS_OUT 0
#define PIO_IN_KEY_HAS_TRI 0
#define PIO_IN_KEY_IRQ -1
#define PIO_IN_KEY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_IN_KEY_IRQ_TYPE "NONE"
#define PIO_IN_KEY_NAME "/dev/pio_in_key"
#define PIO_IN_KEY_RESET_VALUE 0
#define PIO_IN_KEY_SPAN 16
#define PIO_IN_KEY_TYPE "altera_avalon_pio"


/*
 * pio_in_keyboard_data configuration
 *
 */

#define ALT_MODULE_CLASS_pio_in_keyboard_data altera_avalon_pio
#define PIO_IN_KEYBOARD_DATA_BASE 0x41050
#define PIO_IN_KEYBOARD_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_IN_KEYBOARD_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_IN_KEYBOARD_DATA_CAPTURE 0
#define PIO_IN_KEYBOARD_DATA_DATA_WIDTH 8
#define PIO_IN_KEYBOARD_DATA_DO_TEST_BENCH_WIRING 0
#define PIO_IN_KEYBOARD_DATA_DRIVEN_SIM_VALUE 0
#define PIO_IN_KEYBOARD_DATA_EDGE_TYPE "NONE"
#define PIO_IN_KEYBOARD_DATA_FREQ 50000000
#define PIO_IN_KEYBOARD_DATA_HAS_IN 1
#define PIO_IN_KEYBOARD_DATA_HAS_OUT 0
#define PIO_IN_KEYBOARD_DATA_HAS_TRI 0
#define PIO_IN_KEYBOARD_DATA_IRQ -1
#define PIO_IN_KEYBOARD_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_IN_KEYBOARD_DATA_IRQ_TYPE "NONE"
#define PIO_IN_KEYBOARD_DATA_NAME "/dev/pio_in_keyboard_data"
#define PIO_IN_KEYBOARD_DATA_RESET_VALUE 0
#define PIO_IN_KEYBOARD_DATA_SPAN 16
#define PIO_IN_KEYBOARD_DATA_TYPE "altera_avalon_pio"


/*
 * pio_in_keyboard_status configuration
 *
 */

#define ALT_MODULE_CLASS_pio_in_keyboard_status altera_avalon_pio
#define PIO_IN_KEYBOARD_STATUS_BASE 0x41040
#define PIO_IN_KEYBOARD_STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_IN_KEYBOARD_STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_IN_KEYBOARD_STATUS_CAPTURE 0
#define PIO_IN_KEYBOARD_STATUS_DATA_WIDTH 8
#define PIO_IN_KEYBOARD_STATUS_DO_TEST_BENCH_WIRING 0
#define PIO_IN_KEYBOARD_STATUS_DRIVEN_SIM_VALUE 0
#define PIO_IN_KEYBOARD_STATUS_EDGE_TYPE "NONE"
#define PIO_IN_KEYBOARD_STATUS_FREQ 50000000
#define PIO_IN_KEYBOARD_STATUS_HAS_IN 1
#define PIO_IN_KEYBOARD_STATUS_HAS_OUT 0
#define PIO_IN_KEYBOARD_STATUS_HAS_TRI 0
#define PIO_IN_KEYBOARD_STATUS_IRQ -1
#define PIO_IN_KEYBOARD_STATUS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_IN_KEYBOARD_STATUS_IRQ_TYPE "NONE"
#define PIO_IN_KEYBOARD_STATUS_NAME "/dev/pio_in_keyboard_status"
#define PIO_IN_KEYBOARD_STATUS_RESET_VALUE 0
#define PIO_IN_KEYBOARD_STATUS_SPAN 16
#define PIO_IN_KEYBOARD_STATUS_TYPE "altera_avalon_pio"


/*
 * pio_in_sw configuration
 *
 */

#define ALT_MODULE_CLASS_pio_in_sw altera_avalon_pio
#define PIO_IN_SW_BASE 0x41170
#define PIO_IN_SW_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_IN_SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_IN_SW_CAPTURE 0
#define PIO_IN_SW_DATA_WIDTH 18
#define PIO_IN_SW_DO_TEST_BENCH_WIRING 0
#define PIO_IN_SW_DRIVEN_SIM_VALUE 0
#define PIO_IN_SW_EDGE_TYPE "NONE"
#define PIO_IN_SW_FREQ 50000000
#define PIO_IN_SW_HAS_IN 1
#define PIO_IN_SW_HAS_OUT 0
#define PIO_IN_SW_HAS_TRI 0
#define PIO_IN_SW_IRQ -1
#define PIO_IN_SW_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_IN_SW_IRQ_TYPE "NONE"
#define PIO_IN_SW_NAME "/dev/pio_in_sw"
#define PIO_IN_SW_RESET_VALUE 0
#define PIO_IN_SW_SPAN 16
#define PIO_IN_SW_TYPE "altera_avalon_pio"


/*
 * pio_out_eep_scl configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_eep_scl altera_avalon_pio
#define PIO_OUT_EEP_SCL_BASE 0x41090
#define PIO_OUT_EEP_SCL_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_EEP_SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_EEP_SCL_CAPTURE 0
#define PIO_OUT_EEP_SCL_DATA_WIDTH 1
#define PIO_OUT_EEP_SCL_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_EEP_SCL_DRIVEN_SIM_VALUE 0
#define PIO_OUT_EEP_SCL_EDGE_TYPE "NONE"
#define PIO_OUT_EEP_SCL_FREQ 50000000
#define PIO_OUT_EEP_SCL_HAS_IN 0
#define PIO_OUT_EEP_SCL_HAS_OUT 1
#define PIO_OUT_EEP_SCL_HAS_TRI 0
#define PIO_OUT_EEP_SCL_IRQ -1
#define PIO_OUT_EEP_SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_EEP_SCL_IRQ_TYPE "NONE"
#define PIO_OUT_EEP_SCL_NAME "/dev/pio_out_eep_scl"
#define PIO_OUT_EEP_SCL_RESET_VALUE 0
#define PIO_OUT_EEP_SCL_SPAN 16
#define PIO_OUT_EEP_SCL_TYPE "altera_avalon_pio"


/*
 * pio_out_eep_sda_oe configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_eep_sda_oe altera_avalon_pio
#define PIO_OUT_EEP_SDA_OE_BASE 0x41070
#define PIO_OUT_EEP_SDA_OE_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_EEP_SDA_OE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_EEP_SDA_OE_CAPTURE 0
#define PIO_OUT_EEP_SDA_OE_DATA_WIDTH 1
#define PIO_OUT_EEP_SDA_OE_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_EEP_SDA_OE_DRIVEN_SIM_VALUE 0
#define PIO_OUT_EEP_SDA_OE_EDGE_TYPE "NONE"
#define PIO_OUT_EEP_SDA_OE_FREQ 50000000
#define PIO_OUT_EEP_SDA_OE_HAS_IN 0
#define PIO_OUT_EEP_SDA_OE_HAS_OUT 1
#define PIO_OUT_EEP_SDA_OE_HAS_TRI 0
#define PIO_OUT_EEP_SDA_OE_IRQ -1
#define PIO_OUT_EEP_SDA_OE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_EEP_SDA_OE_IRQ_TYPE "NONE"
#define PIO_OUT_EEP_SDA_OE_NAME "/dev/pio_out_eep_sda_oe"
#define PIO_OUT_EEP_SDA_OE_RESET_VALUE 0
#define PIO_OUT_EEP_SDA_OE_SPAN 16
#define PIO_OUT_EEP_SDA_OE_TYPE "altera_avalon_pio"


/*
 * pio_out_eep_sda_out configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_eep_sda_out altera_avalon_pio
#define PIO_OUT_EEP_SDA_OUT_BASE 0x41080
#define PIO_OUT_EEP_SDA_OUT_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_EEP_SDA_OUT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_EEP_SDA_OUT_CAPTURE 0
#define PIO_OUT_EEP_SDA_OUT_DATA_WIDTH 1
#define PIO_OUT_EEP_SDA_OUT_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_EEP_SDA_OUT_DRIVEN_SIM_VALUE 0
#define PIO_OUT_EEP_SDA_OUT_EDGE_TYPE "NONE"
#define PIO_OUT_EEP_SDA_OUT_FREQ 50000000
#define PIO_OUT_EEP_SDA_OUT_HAS_IN 0
#define PIO_OUT_EEP_SDA_OUT_HAS_OUT 1
#define PIO_OUT_EEP_SDA_OUT_HAS_TRI 0
#define PIO_OUT_EEP_SDA_OUT_IRQ -1
#define PIO_OUT_EEP_SDA_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_EEP_SDA_OUT_IRQ_TYPE "NONE"
#define PIO_OUT_EEP_SDA_OUT_NAME "/dev/pio_out_eep_sda_out"
#define PIO_OUT_EEP_SDA_OUT_RESET_VALUE 0
#define PIO_OUT_EEP_SDA_OUT_SPAN 16
#define PIO_OUT_EEP_SDA_OUT_TYPE "altera_avalon_pio"


/*
 * pio_out_hex0 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex0 altera_avalon_pio
#define PIO_OUT_HEX0_BASE 0x41130
#define PIO_OUT_HEX0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX0_CAPTURE 0
#define PIO_OUT_HEX0_DATA_WIDTH 8
#define PIO_OUT_HEX0_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX0_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX0_EDGE_TYPE "NONE"
#define PIO_OUT_HEX0_FREQ 50000000
#define PIO_OUT_HEX0_HAS_IN 0
#define PIO_OUT_HEX0_HAS_OUT 1
#define PIO_OUT_HEX0_HAS_TRI 0
#define PIO_OUT_HEX0_IRQ -1
#define PIO_OUT_HEX0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX0_IRQ_TYPE "NONE"
#define PIO_OUT_HEX0_NAME "/dev/pio_out_hex0"
#define PIO_OUT_HEX0_RESET_VALUE 0
#define PIO_OUT_HEX0_SPAN 16
#define PIO_OUT_HEX0_TYPE "altera_avalon_pio"


/*
 * pio_out_hex1 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex1 altera_avalon_pio
#define PIO_OUT_HEX1_BASE 0x41120
#define PIO_OUT_HEX1_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX1_CAPTURE 0
#define PIO_OUT_HEX1_DATA_WIDTH 8
#define PIO_OUT_HEX1_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX1_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX1_EDGE_TYPE "NONE"
#define PIO_OUT_HEX1_FREQ 50000000
#define PIO_OUT_HEX1_HAS_IN 0
#define PIO_OUT_HEX1_HAS_OUT 1
#define PIO_OUT_HEX1_HAS_TRI 0
#define PIO_OUT_HEX1_IRQ -1
#define PIO_OUT_HEX1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX1_IRQ_TYPE "NONE"
#define PIO_OUT_HEX1_NAME "/dev/pio_out_hex1"
#define PIO_OUT_HEX1_RESET_VALUE 0
#define PIO_OUT_HEX1_SPAN 16
#define PIO_OUT_HEX1_TYPE "altera_avalon_pio"


/*
 * pio_out_hex2 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex2 altera_avalon_pio
#define PIO_OUT_HEX2_BASE 0x41110
#define PIO_OUT_HEX2_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX2_CAPTURE 0
#define PIO_OUT_HEX2_DATA_WIDTH 8
#define PIO_OUT_HEX2_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX2_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX2_EDGE_TYPE "NONE"
#define PIO_OUT_HEX2_FREQ 50000000
#define PIO_OUT_HEX2_HAS_IN 0
#define PIO_OUT_HEX2_HAS_OUT 1
#define PIO_OUT_HEX2_HAS_TRI 0
#define PIO_OUT_HEX2_IRQ -1
#define PIO_OUT_HEX2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX2_IRQ_TYPE "NONE"
#define PIO_OUT_HEX2_NAME "/dev/pio_out_hex2"
#define PIO_OUT_HEX2_RESET_VALUE 0
#define PIO_OUT_HEX2_SPAN 16
#define PIO_OUT_HEX2_TYPE "altera_avalon_pio"


/*
 * pio_out_hex3 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex3 altera_avalon_pio
#define PIO_OUT_HEX3_BASE 0x41100
#define PIO_OUT_HEX3_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX3_CAPTURE 0
#define PIO_OUT_HEX3_DATA_WIDTH 8
#define PIO_OUT_HEX3_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX3_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX3_EDGE_TYPE "NONE"
#define PIO_OUT_HEX3_FREQ 50000000
#define PIO_OUT_HEX3_HAS_IN 0
#define PIO_OUT_HEX3_HAS_OUT 1
#define PIO_OUT_HEX3_HAS_TRI 0
#define PIO_OUT_HEX3_IRQ -1
#define PIO_OUT_HEX3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX3_IRQ_TYPE "NONE"
#define PIO_OUT_HEX3_NAME "/dev/pio_out_hex3"
#define PIO_OUT_HEX3_RESET_VALUE 0
#define PIO_OUT_HEX3_SPAN 16
#define PIO_OUT_HEX3_TYPE "altera_avalon_pio"


/*
 * pio_out_hex4 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex4 altera_avalon_pio
#define PIO_OUT_HEX4_BASE 0x410f0
#define PIO_OUT_HEX4_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX4_CAPTURE 0
#define PIO_OUT_HEX4_DATA_WIDTH 8
#define PIO_OUT_HEX4_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX4_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX4_EDGE_TYPE "NONE"
#define PIO_OUT_HEX4_FREQ 50000000
#define PIO_OUT_HEX4_HAS_IN 0
#define PIO_OUT_HEX4_HAS_OUT 1
#define PIO_OUT_HEX4_HAS_TRI 0
#define PIO_OUT_HEX4_IRQ -1
#define PIO_OUT_HEX4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX4_IRQ_TYPE "NONE"
#define PIO_OUT_HEX4_NAME "/dev/pio_out_hex4"
#define PIO_OUT_HEX4_RESET_VALUE 0
#define PIO_OUT_HEX4_SPAN 16
#define PIO_OUT_HEX4_TYPE "altera_avalon_pio"


/*
 * pio_out_hex5 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex5 altera_avalon_pio
#define PIO_OUT_HEX5_BASE 0x410e0
#define PIO_OUT_HEX5_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX5_CAPTURE 0
#define PIO_OUT_HEX5_DATA_WIDTH 8
#define PIO_OUT_HEX5_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX5_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX5_EDGE_TYPE "NONE"
#define PIO_OUT_HEX5_FREQ 50000000
#define PIO_OUT_HEX5_HAS_IN 0
#define PIO_OUT_HEX5_HAS_OUT 1
#define PIO_OUT_HEX5_HAS_TRI 0
#define PIO_OUT_HEX5_IRQ -1
#define PIO_OUT_HEX5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX5_IRQ_TYPE "NONE"
#define PIO_OUT_HEX5_NAME "/dev/pio_out_hex5"
#define PIO_OUT_HEX5_RESET_VALUE 0
#define PIO_OUT_HEX5_SPAN 16
#define PIO_OUT_HEX5_TYPE "altera_avalon_pio"


/*
 * pio_out_hex6 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex6 altera_avalon_pio
#define PIO_OUT_HEX6_BASE 0x410d0
#define PIO_OUT_HEX6_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX6_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX6_CAPTURE 0
#define PIO_OUT_HEX6_DATA_WIDTH 8
#define PIO_OUT_HEX6_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX6_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX6_EDGE_TYPE "NONE"
#define PIO_OUT_HEX6_FREQ 50000000
#define PIO_OUT_HEX6_HAS_IN 0
#define PIO_OUT_HEX6_HAS_OUT 1
#define PIO_OUT_HEX6_HAS_TRI 0
#define PIO_OUT_HEX6_IRQ -1
#define PIO_OUT_HEX6_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX6_IRQ_TYPE "NONE"
#define PIO_OUT_HEX6_NAME "/dev/pio_out_hex6"
#define PIO_OUT_HEX6_RESET_VALUE 0
#define PIO_OUT_HEX6_SPAN 16
#define PIO_OUT_HEX6_TYPE "altera_avalon_pio"


/*
 * pio_out_hex7 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_hex7 altera_avalon_pio
#define PIO_OUT_HEX7_BASE 0x410c0
#define PIO_OUT_HEX7_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_HEX7_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_HEX7_CAPTURE 0
#define PIO_OUT_HEX7_DATA_WIDTH 8
#define PIO_OUT_HEX7_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_HEX7_DRIVEN_SIM_VALUE 0
#define PIO_OUT_HEX7_EDGE_TYPE "NONE"
#define PIO_OUT_HEX7_FREQ 50000000
#define PIO_OUT_HEX7_HAS_IN 0
#define PIO_OUT_HEX7_HAS_OUT 1
#define PIO_OUT_HEX7_HAS_TRI 0
#define PIO_OUT_HEX7_IRQ -1
#define PIO_OUT_HEX7_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_HEX7_IRQ_TYPE "NONE"
#define PIO_OUT_HEX7_NAME "/dev/pio_out_hex7"
#define PIO_OUT_HEX7_RESET_VALUE 0
#define PIO_OUT_HEX7_SPAN 16
#define PIO_OUT_HEX7_TYPE "altera_avalon_pio"


/*
 * pio_out_keyboard_ack configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_keyboard_ack altera_avalon_pio
#define PIO_OUT_KEYBOARD_ACK_BASE 0x41030
#define PIO_OUT_KEYBOARD_ACK_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_KEYBOARD_ACK_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_KEYBOARD_ACK_CAPTURE 0
#define PIO_OUT_KEYBOARD_ACK_DATA_WIDTH 1
#define PIO_OUT_KEYBOARD_ACK_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_KEYBOARD_ACK_DRIVEN_SIM_VALUE 0
#define PIO_OUT_KEYBOARD_ACK_EDGE_TYPE "NONE"
#define PIO_OUT_KEYBOARD_ACK_FREQ 50000000
#define PIO_OUT_KEYBOARD_ACK_HAS_IN 0
#define PIO_OUT_KEYBOARD_ACK_HAS_OUT 1
#define PIO_OUT_KEYBOARD_ACK_HAS_TRI 0
#define PIO_OUT_KEYBOARD_ACK_IRQ -1
#define PIO_OUT_KEYBOARD_ACK_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_KEYBOARD_ACK_IRQ_TYPE "NONE"
#define PIO_OUT_KEYBOARD_ACK_NAME "/dev/pio_out_keyboard_ack"
#define PIO_OUT_KEYBOARD_ACK_RESET_VALUE 0
#define PIO_OUT_KEYBOARD_ACK_SPAN 16
#define PIO_OUT_KEYBOARD_ACK_TYPE "altera_avalon_pio"


/*
 * pio_out_lcd_ctrl configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_lcd_ctrl altera_avalon_pio
#define PIO_OUT_LCD_CTRL_BASE 0x410a0
#define PIO_OUT_LCD_CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LCD_CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LCD_CTRL_CAPTURE 0
#define PIO_OUT_LCD_CTRL_DATA_WIDTH 5
#define PIO_OUT_LCD_CTRL_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LCD_CTRL_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LCD_CTRL_EDGE_TYPE "NONE"
#define PIO_OUT_LCD_CTRL_FREQ 50000000
#define PIO_OUT_LCD_CTRL_HAS_IN 0
#define PIO_OUT_LCD_CTRL_HAS_OUT 1
#define PIO_OUT_LCD_CTRL_HAS_TRI 0
#define PIO_OUT_LCD_CTRL_IRQ -1
#define PIO_OUT_LCD_CTRL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LCD_CTRL_IRQ_TYPE "NONE"
#define PIO_OUT_LCD_CTRL_NAME "/dev/pio_out_lcd_ctrl"
#define PIO_OUT_LCD_CTRL_RESET_VALUE 0
#define PIO_OUT_LCD_CTRL_SPAN 16
#define PIO_OUT_LCD_CTRL_TYPE "altera_avalon_pio"


/*
 * pio_out_lcd_data configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_lcd_data altera_avalon_pio
#define PIO_OUT_LCD_DATA_BASE 0x410b0
#define PIO_OUT_LCD_DATA_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LCD_DATA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LCD_DATA_CAPTURE 0
#define PIO_OUT_LCD_DATA_DATA_WIDTH 8
#define PIO_OUT_LCD_DATA_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LCD_DATA_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LCD_DATA_EDGE_TYPE "NONE"
#define PIO_OUT_LCD_DATA_FREQ 50000000
#define PIO_OUT_LCD_DATA_HAS_IN 0
#define PIO_OUT_LCD_DATA_HAS_OUT 1
#define PIO_OUT_LCD_DATA_HAS_TRI 0
#define PIO_OUT_LCD_DATA_IRQ -1
#define PIO_OUT_LCD_DATA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LCD_DATA_IRQ_TYPE "NONE"
#define PIO_OUT_LCD_DATA_NAME "/dev/pio_out_lcd_data"
#define PIO_OUT_LCD_DATA_RESET_VALUE 0
#define PIO_OUT_LCD_DATA_SPAN 16
#define PIO_OUT_LCD_DATA_TYPE "altera_avalon_pio"


/*
 * pio_out_ledg configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_ledg altera_avalon_pio
#define PIO_OUT_LEDG_BASE 0x41140
#define PIO_OUT_LEDG_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LEDG_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LEDG_CAPTURE 0
#define PIO_OUT_LEDG_DATA_WIDTH 8
#define PIO_OUT_LEDG_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LEDG_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LEDG_EDGE_TYPE "NONE"
#define PIO_OUT_LEDG_FREQ 50000000
#define PIO_OUT_LEDG_HAS_IN 0
#define PIO_OUT_LEDG_HAS_OUT 1
#define PIO_OUT_LEDG_HAS_TRI 0
#define PIO_OUT_LEDG_IRQ -1
#define PIO_OUT_LEDG_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LEDG_IRQ_TYPE "NONE"
#define PIO_OUT_LEDG_NAME "/dev/pio_out_ledg"
#define PIO_OUT_LEDG_RESET_VALUE 0
#define PIO_OUT_LEDG_SPAN 16
#define PIO_OUT_LEDG_TYPE "altera_avalon_pio"


/*
 * pio_out_ledg8 configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_ledg8 altera_avalon_pio
#define PIO_OUT_LEDG8_BASE 0x41190
#define PIO_OUT_LEDG8_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LEDG8_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LEDG8_CAPTURE 0
#define PIO_OUT_LEDG8_DATA_WIDTH 1
#define PIO_OUT_LEDG8_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LEDG8_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LEDG8_EDGE_TYPE "NONE"
#define PIO_OUT_LEDG8_FREQ 50000000
#define PIO_OUT_LEDG8_HAS_IN 0
#define PIO_OUT_LEDG8_HAS_OUT 1
#define PIO_OUT_LEDG8_HAS_TRI 0
#define PIO_OUT_LEDG8_IRQ -1
#define PIO_OUT_LEDG8_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LEDG8_IRQ_TYPE "NONE"
#define PIO_OUT_LEDG8_NAME "/dev/pio_out_ledg8"
#define PIO_OUT_LEDG8_RESET_VALUE 0
#define PIO_OUT_LEDG8_SPAN 16
#define PIO_OUT_LEDG8_TYPE "altera_avalon_pio"


/*
 * pio_out_ledr configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_ledr altera_avalon_pio
#define PIO_OUT_LEDR_BASE 0x41150
#define PIO_OUT_LEDR_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LEDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LEDR_CAPTURE 0
#define PIO_OUT_LEDR_DATA_WIDTH 18
#define PIO_OUT_LEDR_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LEDR_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LEDR_EDGE_TYPE "NONE"
#define PIO_OUT_LEDR_FREQ 50000000
#define PIO_OUT_LEDR_HAS_IN 0
#define PIO_OUT_LEDR_HAS_OUT 1
#define PIO_OUT_LEDR_HAS_TRI 0
#define PIO_OUT_LEDR_IRQ -1
#define PIO_OUT_LEDR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LEDR_IRQ_TYPE "NONE"
#define PIO_OUT_LEDR_NAME "/dev/pio_out_ledr"
#define PIO_OUT_LEDR_RESET_VALUE 0
#define PIO_OUT_LEDR_SPAN 16
#define PIO_OUT_LEDR_TYPE "altera_avalon_pio"


/*
 * pio_out_ledr_flag configuration
 *
 */

#define ALT_MODULE_CLASS_pio_out_ledr_flag altera_avalon_pio
#define PIO_OUT_LEDR_FLAG_BASE 0x41020
#define PIO_OUT_LEDR_FLAG_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_OUT_LEDR_FLAG_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_OUT_LEDR_FLAG_CAPTURE 0
#define PIO_OUT_LEDR_FLAG_DATA_WIDTH 8
#define PIO_OUT_LEDR_FLAG_DO_TEST_BENCH_WIRING 0
#define PIO_OUT_LEDR_FLAG_DRIVEN_SIM_VALUE 0
#define PIO_OUT_LEDR_FLAG_EDGE_TYPE "NONE"
#define PIO_OUT_LEDR_FLAG_FREQ 50000000
#define PIO_OUT_LEDR_FLAG_HAS_IN 0
#define PIO_OUT_LEDR_FLAG_HAS_OUT 1
#define PIO_OUT_LEDR_FLAG_HAS_TRI 0
#define PIO_OUT_LEDR_FLAG_IRQ -1
#define PIO_OUT_LEDR_FLAG_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PIO_OUT_LEDR_FLAG_IRQ_TYPE "NONE"
#define PIO_OUT_LEDR_FLAG_NAME "/dev/pio_out_ledr_flag"
#define PIO_OUT_LEDR_FLAG_RESET_VALUE 0
#define PIO_OUT_LEDR_FLAG_SPAN 16
#define PIO_OUT_LEDR_FLAG_TYPE "altera_avalon_pio"


/*
 * spi_sdcard configuration
 *
 */

#define ALT_MODULE_CLASS_spi_sdcard altera_avalon_spi
#define SPI_SDCARD_BASE 0x41000
#define SPI_SDCARD_CLOCKMULT 1
#define SPI_SDCARD_CLOCKPHASE 0
#define SPI_SDCARD_CLOCKPOLARITY 0
#define SPI_SDCARD_CLOCKUNITS "Hz"
#define SPI_SDCARD_DATABITS 8
#define SPI_SDCARD_DATAWIDTH 16
#define SPI_SDCARD_DELAYMULT "1.0E-9"
#define SPI_SDCARD_DELAYUNITS "ns"
#define SPI_SDCARD_EXTRADELAY 0
#define SPI_SDCARD_INSERT_SYNC 0
#define SPI_SDCARD_IRQ 1
#define SPI_SDCARD_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_SDCARD_ISMASTER 1
#define SPI_SDCARD_LSBFIRST 0
#define SPI_SDCARD_NAME "/dev/spi_sdcard"
#define SPI_SDCARD_NUMSLAVES 1
#define SPI_SDCARD_PREFIX "spi_"
#define SPI_SDCARD_SPAN 32
#define SPI_SDCARD_SYNC_REG_DEPTH 2
#define SPI_SDCARD_TARGETCLOCK 4000u
#define SPI_SDCARD_TARGETSSDELAY "0.0"
#define SPI_SDCARD_TYPE "altera_avalon_spi"


/*
 * sysid_qsys configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys altera_avalon_sysid_qsys
#define SYSID_QSYS_BASE 0x41180
#define SYSID_QSYS_ID 260
#define SYSID_QSYS_IRQ -1
#define SYSID_QSYS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_NAME "/dev/sysid_qsys"
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_TIMESTAMP 1781903384
#define SYSID_QSYS_TYPE "altera_avalon_sysid_qsys"


/*
 * timer configuration
 *
 */

#define ALT_MODULE_CLASS_timer altera_avalon_timer
#define TIMER_ALWAYS_RUN 0
#define TIMER_BASE 0x0
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 0
#define TIMER_FREQ 50000000
#define TIMER_IRQ 2
#define TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_LOAD_VALUE 49999
#define TIMER_MULT 0.0010
#define TIMER_NAME "/dev/timer"
#define TIMER_PERIOD 1
#define TIMER_PERIOD_UNITS "ms"
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_SPAN 32
#define TIMER_TICKS_PER_SEC 1000.0
#define TIMER_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
