// nios.v

// Generated using ACDS version 13.1 162 at 2026.06.21.04:37:15

`timescale 1 ps / 1 ps
module nios (
		input  wire        clk_clk,                                           //                                        clk.clk
		input  wire        reset_reset_n,                                     //                                      reset.reset_n
		input  wire        pio_in_eep_sda_in_external_connection_export,      //      pio_in_eep_sda_in_external_connection.export
		output wire        pio_out_eep_sda_oe_external_connection_export,     //     pio_out_eep_sda_oe_external_connection.export
		output wire        pio_out_eep_sda_out_external_connection_export,    //    pio_out_eep_sda_out_external_connection.export
		output wire        pio_out_eep_scl_external_connection_export,        //        pio_out_eep_scl_external_connection.export
		output wire [4:0]  pio_out_lcd_ctrl_external_connection_export,       //       pio_out_lcd_ctrl_external_connection.export
		output wire [7:0]  pio_out_lcd_data_external_connection_export,       //       pio_out_lcd_data_external_connection.export
		output wire [7:0]  pio_out_hex7_external_connection_export,           //           pio_out_hex7_external_connection.export
		output wire [7:0]  pio_out_hex6_external_connection_export,           //           pio_out_hex6_external_connection.export
		output wire [7:0]  pio_out_hex5_external_connection_export,           //           pio_out_hex5_external_connection.export
		output wire [7:0]  pio_out_hex4_external_connection_export,           //           pio_out_hex4_external_connection.export
		output wire [7:0]  pio_out_hex3_external_connection_export,           //           pio_out_hex3_external_connection.export
		output wire [7:0]  pio_out_hex2_external_connection_export,           //           pio_out_hex2_external_connection.export
		output wire [7:0]  pio_out_hex1_external_connection_export,           //           pio_out_hex1_external_connection.export
		output wire [7:0]  pio_out_hex0_external_connection_export,           //           pio_out_hex0_external_connection.export
		output wire [7:0]  pio_out_ledg_external_connection_export,           //           pio_out_ledg_external_connection.export
		output wire        pio_out_ledg8_external_connection_export,          //          pio_out_ledg8_external_connection.export
		output wire [17:0] pio_out_ledr_external_connection_export,           //           pio_out_ledr_external_connection.export
		input  wire [3:0]  pio_in_key_external_connection_export,             //             pio_in_key_external_connection.export
		input  wire [17:0] pio_in_sw_external_connection_export,              //              pio_in_sw_external_connection.export
		input  wire [7:0]  pio_in_keyboard_data_external_connection_export,   //   pio_in_keyboard_data_external_connection.export
		input  wire [7:0]  pio_in_keyboard_status_external_connection_export, // pio_in_keyboard_status_external_connection.export
		output wire        pio_out_keyboard_ack_external_connection_export,   //   pio_out_keyboard_ack_external_connection.export
		input  wire        spi_sdcard_external_MISO,                          //                        spi_sdcard_external.MISO
		output wire        spi_sdcard_external_MOSI,                          //                                           .MOSI
		output wire        spi_sdcard_external_SCLK,                          //                                           .SCLK
		output wire        spi_sdcard_external_SS_n,                          //                                           .SS_n
		output wire [7:0]  pio_out_ledr_flag_external_connection_export       //      pio_out_ledr_flag_external_connection.export
	);

	wire   [0:0] mm_interconnect_0_sysid_qsys_control_slave_address;        // mm_interconnect_0:sysid_qsys_control_slave_address -> sysid_qsys:address
	wire  [31:0] mm_interconnect_0_sysid_qsys_control_slave_readdata;       // sysid_qsys:readdata -> mm_interconnect_0:sysid_qsys_control_slave_readdata
	wire  [31:0] mm_interconnect_0_pio_out_eep_sda_oe_s1_writedata;         // mm_interconnect_0:pio_out_eep_sda_oe_s1_writedata -> pio_out_eep_sda_oe:writedata
	wire   [1:0] mm_interconnect_0_pio_out_eep_sda_oe_s1_address;           // mm_interconnect_0:pio_out_eep_sda_oe_s1_address -> pio_out_eep_sda_oe:address
	wire         mm_interconnect_0_pio_out_eep_sda_oe_s1_chipselect;        // mm_interconnect_0:pio_out_eep_sda_oe_s1_chipselect -> pio_out_eep_sda_oe:chipselect
	wire         mm_interconnect_0_pio_out_eep_sda_oe_s1_write;             // mm_interconnect_0:pio_out_eep_sda_oe_s1_write -> pio_out_eep_sda_oe:write_n
	wire  [31:0] mm_interconnect_0_pio_out_eep_sda_oe_s1_readdata;          // pio_out_eep_sda_oe:readdata -> mm_interconnect_0:pio_out_eep_sda_oe_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_ledr_s1_writedata;               // mm_interconnect_0:pio_out_ledr_s1_writedata -> pio_out_ledr:writedata
	wire   [1:0] mm_interconnect_0_pio_out_ledr_s1_address;                 // mm_interconnect_0:pio_out_ledr_s1_address -> pio_out_ledr:address
	wire         mm_interconnect_0_pio_out_ledr_s1_chipselect;              // mm_interconnect_0:pio_out_ledr_s1_chipselect -> pio_out_ledr:chipselect
	wire         mm_interconnect_0_pio_out_ledr_s1_write;                   // mm_interconnect_0:pio_out_ledr_s1_write -> pio_out_ledr:write_n
	wire  [31:0] mm_interconnect_0_pio_out_ledr_s1_readdata;                // pio_out_ledr:readdata -> mm_interconnect_0:pio_out_ledr_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_in_keyboard_status_s1_address;       // mm_interconnect_0:pio_in_keyboard_status_s1_address -> pio_in_keyboard_status:address
	wire  [31:0] mm_interconnect_0_pio_in_keyboard_status_s1_readdata;      // pio_in_keyboard_status:readdata -> mm_interconnect_0:pio_in_keyboard_status_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_lcd_data_s1_writedata;           // mm_interconnect_0:pio_out_lcd_data_s1_writedata -> pio_out_lcd_data:writedata
	wire   [1:0] mm_interconnect_0_pio_out_lcd_data_s1_address;             // mm_interconnect_0:pio_out_lcd_data_s1_address -> pio_out_lcd_data:address
	wire         mm_interconnect_0_pio_out_lcd_data_s1_chipselect;          // mm_interconnect_0:pio_out_lcd_data_s1_chipselect -> pio_out_lcd_data:chipselect
	wire         mm_interconnect_0_pio_out_lcd_data_s1_write;               // mm_interconnect_0:pio_out_lcd_data_s1_write -> pio_out_lcd_data:write_n
	wire  [31:0] mm_interconnect_0_pio_out_lcd_data_s1_readdata;            // pio_out_lcd_data:readdata -> mm_interconnect_0:pio_out_lcd_data_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex4_s1_writedata;               // mm_interconnect_0:pio_out_hex4_s1_writedata -> pio_out_hex4:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex4_s1_address;                 // mm_interconnect_0:pio_out_hex4_s1_address -> pio_out_hex4:address
	wire         mm_interconnect_0_pio_out_hex4_s1_chipselect;              // mm_interconnect_0:pio_out_hex4_s1_chipselect -> pio_out_hex4:chipselect
	wire         mm_interconnect_0_pio_out_hex4_s1_write;                   // mm_interconnect_0:pio_out_hex4_s1_write -> pio_out_hex4:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex4_s1_readdata;                // pio_out_hex4:readdata -> mm_interconnect_0:pio_out_hex4_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_in_eep_sda_in_s1_address;            // mm_interconnect_0:pio_in_eep_sda_in_s1_address -> pio_in_eep_sda_in:address
	wire  [31:0] mm_interconnect_0_pio_in_eep_sda_in_s1_readdata;           // pio_in_eep_sda_in:readdata -> mm_interconnect_0:pio_in_eep_sda_in_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_in_keyboard_data_s1_address;         // mm_interconnect_0:pio_in_keyboard_data_s1_address -> pio_in_keyboard_data:address
	wire  [31:0] mm_interconnect_0_pio_in_keyboard_data_s1_readdata;        // pio_in_keyboard_data:readdata -> mm_interconnect_0:pio_in_keyboard_data_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex0_s1_writedata;               // mm_interconnect_0:pio_out_hex0_s1_writedata -> pio_out_hex0:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex0_s1_address;                 // mm_interconnect_0:pio_out_hex0_s1_address -> pio_out_hex0:address
	wire         mm_interconnect_0_pio_out_hex0_s1_chipselect;              // mm_interconnect_0:pio_out_hex0_s1_chipselect -> pio_out_hex0:chipselect
	wire         mm_interconnect_0_pio_out_hex0_s1_write;                   // mm_interconnect_0:pio_out_hex0_s1_write -> pio_out_hex0:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex0_s1_readdata;                // pio_out_hex0:readdata -> mm_interconnect_0:pio_out_hex0_s1_readdata
	wire         cpu_data_master_waitrequest;                               // mm_interconnect_0:cpu_data_master_waitrequest -> cpu:d_waitrequest
	wire  [31:0] cpu_data_master_writedata;                                 // cpu:d_writedata -> mm_interconnect_0:cpu_data_master_writedata
	wire  [19:0] cpu_data_master_address;                                   // cpu:d_address -> mm_interconnect_0:cpu_data_master_address
	wire         cpu_data_master_write;                                     // cpu:d_write -> mm_interconnect_0:cpu_data_master_write
	wire         cpu_data_master_read;                                      // cpu:d_read -> mm_interconnect_0:cpu_data_master_read
	wire  [31:0] cpu_data_master_readdata;                                  // mm_interconnect_0:cpu_data_master_readdata -> cpu:d_readdata
	wire         cpu_data_master_debugaccess;                               // cpu:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:cpu_data_master_debugaccess
	wire   [3:0] cpu_data_master_byteenable;                                // cpu:d_byteenable -> mm_interconnect_0:cpu_data_master_byteenable
	wire         cpu_instruction_master_waitrequest;                        // mm_interconnect_0:cpu_instruction_master_waitrequest -> cpu:i_waitrequest
	wire  [19:0] cpu_instruction_master_address;                            // cpu:i_address -> mm_interconnect_0:cpu_instruction_master_address
	wire         cpu_instruction_master_read;                               // cpu:i_read -> mm_interconnect_0:cpu_instruction_master_read
	wire  [31:0] cpu_instruction_master_readdata;                           // mm_interconnect_0:cpu_instruction_master_readdata -> cpu:i_readdata
	wire  [31:0] mm_interconnect_0_pio_out_keyboard_ack_s1_writedata;       // mm_interconnect_0:pio_out_keyboard_ack_s1_writedata -> pio_out_keyboard_ack:writedata
	wire   [1:0] mm_interconnect_0_pio_out_keyboard_ack_s1_address;         // mm_interconnect_0:pio_out_keyboard_ack_s1_address -> pio_out_keyboard_ack:address
	wire         mm_interconnect_0_pio_out_keyboard_ack_s1_chipselect;      // mm_interconnect_0:pio_out_keyboard_ack_s1_chipselect -> pio_out_keyboard_ack:chipselect
	wire         mm_interconnect_0_pio_out_keyboard_ack_s1_write;           // mm_interconnect_0:pio_out_keyboard_ack_s1_write -> pio_out_keyboard_ack:write_n
	wire  [31:0] mm_interconnect_0_pio_out_keyboard_ack_s1_readdata;        // pio_out_keyboard_ack:readdata -> mm_interconnect_0:pio_out_keyboard_ack_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_in_sw_s1_address;                    // mm_interconnect_0:pio_in_sw_s1_address -> pio_in_sw:address
	wire  [31:0] mm_interconnect_0_pio_in_sw_s1_readdata;                   // pio_in_sw:readdata -> mm_interconnect_0:pio_in_sw_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_ledg8_s1_writedata;              // mm_interconnect_0:pio_out_ledg8_s1_writedata -> pio_out_ledg8:writedata
	wire   [1:0] mm_interconnect_0_pio_out_ledg8_s1_address;                // mm_interconnect_0:pio_out_ledg8_s1_address -> pio_out_ledg8:address
	wire         mm_interconnect_0_pio_out_ledg8_s1_chipselect;             // mm_interconnect_0:pio_out_ledg8_s1_chipselect -> pio_out_ledg8:chipselect
	wire         mm_interconnect_0_pio_out_ledg8_s1_write;                  // mm_interconnect_0:pio_out_ledg8_s1_write -> pio_out_ledg8:write_n
	wire  [31:0] mm_interconnect_0_pio_out_ledg8_s1_readdata;               // pio_out_ledg8:readdata -> mm_interconnect_0:pio_out_ledg8_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex1_s1_writedata;               // mm_interconnect_0:pio_out_hex1_s1_writedata -> pio_out_hex1:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex1_s1_address;                 // mm_interconnect_0:pio_out_hex1_s1_address -> pio_out_hex1:address
	wire         mm_interconnect_0_pio_out_hex1_s1_chipselect;              // mm_interconnect_0:pio_out_hex1_s1_chipselect -> pio_out_hex1:chipselect
	wire         mm_interconnect_0_pio_out_hex1_s1_write;                   // mm_interconnect_0:pio_out_hex1_s1_write -> pio_out_hex1:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex1_s1_readdata;                // pio_out_hex1:readdata -> mm_interconnect_0:pio_out_hex1_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex3_s1_writedata;               // mm_interconnect_0:pio_out_hex3_s1_writedata -> pio_out_hex3:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex3_s1_address;                 // mm_interconnect_0:pio_out_hex3_s1_address -> pio_out_hex3:address
	wire         mm_interconnect_0_pio_out_hex3_s1_chipselect;              // mm_interconnect_0:pio_out_hex3_s1_chipselect -> pio_out_hex3:chipselect
	wire         mm_interconnect_0_pio_out_hex3_s1_write;                   // mm_interconnect_0:pio_out_hex3_s1_write -> pio_out_hex3:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex3_s1_readdata;                // pio_out_hex3:readdata -> mm_interconnect_0:pio_out_hex3_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_lcd_ctrl_s1_writedata;           // mm_interconnect_0:pio_out_lcd_ctrl_s1_writedata -> pio_out_lcd_ctrl:writedata
	wire   [1:0] mm_interconnect_0_pio_out_lcd_ctrl_s1_address;             // mm_interconnect_0:pio_out_lcd_ctrl_s1_address -> pio_out_lcd_ctrl:address
	wire         mm_interconnect_0_pio_out_lcd_ctrl_s1_chipselect;          // mm_interconnect_0:pio_out_lcd_ctrl_s1_chipselect -> pio_out_lcd_ctrl:chipselect
	wire         mm_interconnect_0_pio_out_lcd_ctrl_s1_write;               // mm_interconnect_0:pio_out_lcd_ctrl_s1_write -> pio_out_lcd_ctrl:write_n
	wire  [31:0] mm_interconnect_0_pio_out_lcd_ctrl_s1_readdata;            // pio_out_lcd_ctrl:readdata -> mm_interconnect_0:pio_out_lcd_ctrl_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_eep_scl_s1_writedata;            // mm_interconnect_0:pio_out_eep_scl_s1_writedata -> pio_out_eep_scl:writedata
	wire   [1:0] mm_interconnect_0_pio_out_eep_scl_s1_address;              // mm_interconnect_0:pio_out_eep_scl_s1_address -> pio_out_eep_scl:address
	wire         mm_interconnect_0_pio_out_eep_scl_s1_chipselect;           // mm_interconnect_0:pio_out_eep_scl_s1_chipselect -> pio_out_eep_scl:chipselect
	wire         mm_interconnect_0_pio_out_eep_scl_s1_write;                // mm_interconnect_0:pio_out_eep_scl_s1_write -> pio_out_eep_scl:write_n
	wire  [31:0] mm_interconnect_0_pio_out_eep_scl_s1_readdata;             // pio_out_eep_scl:readdata -> mm_interconnect_0:pio_out_eep_scl_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex5_s1_writedata;               // mm_interconnect_0:pio_out_hex5_s1_writedata -> pio_out_hex5:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex5_s1_address;                 // mm_interconnect_0:pio_out_hex5_s1_address -> pio_out_hex5:address
	wire         mm_interconnect_0_pio_out_hex5_s1_chipselect;              // mm_interconnect_0:pio_out_hex5_s1_chipselect -> pio_out_hex5:chipselect
	wire         mm_interconnect_0_pio_out_hex5_s1_write;                   // mm_interconnect_0:pio_out_hex5_s1_write -> pio_out_hex5:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex5_s1_readdata;                // pio_out_hex5:readdata -> mm_interconnect_0:pio_out_hex5_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_ledg_s1_writedata;               // mm_interconnect_0:pio_out_ledg_s1_writedata -> pio_out_ledg:writedata
	wire   [1:0] mm_interconnect_0_pio_out_ledg_s1_address;                 // mm_interconnect_0:pio_out_ledg_s1_address -> pio_out_ledg:address
	wire         mm_interconnect_0_pio_out_ledg_s1_chipselect;              // mm_interconnect_0:pio_out_ledg_s1_chipselect -> pio_out_ledg:chipselect
	wire         mm_interconnect_0_pio_out_ledg_s1_write;                   // mm_interconnect_0:pio_out_ledg_s1_write -> pio_out_ledg:write_n
	wire  [31:0] mm_interconnect_0_pio_out_ledg_s1_readdata;                // pio_out_ledg:readdata -> mm_interconnect_0:pio_out_ledg_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex6_s1_writedata;               // mm_interconnect_0:pio_out_hex6_s1_writedata -> pio_out_hex6:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex6_s1_address;                 // mm_interconnect_0:pio_out_hex6_s1_address -> pio_out_hex6:address
	wire         mm_interconnect_0_pio_out_hex6_s1_chipselect;              // mm_interconnect_0:pio_out_hex6_s1_chipselect -> pio_out_hex6:chipselect
	wire         mm_interconnect_0_pio_out_hex6_s1_write;                   // mm_interconnect_0:pio_out_hex6_s1_write -> pio_out_hex6:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex6_s1_readdata;                // pio_out_hex6:readdata -> mm_interconnect_0:pio_out_hex6_s1_readdata
	wire  [15:0] mm_interconnect_0_spi_sdcard_spi_control_port_writedata;   // mm_interconnect_0:spi_sdcard_spi_control_port_writedata -> spi_sdcard:data_from_cpu
	wire   [2:0] mm_interconnect_0_spi_sdcard_spi_control_port_address;     // mm_interconnect_0:spi_sdcard_spi_control_port_address -> spi_sdcard:mem_addr
	wire         mm_interconnect_0_spi_sdcard_spi_control_port_chipselect;  // mm_interconnect_0:spi_sdcard_spi_control_port_chipselect -> spi_sdcard:spi_select
	wire         mm_interconnect_0_spi_sdcard_spi_control_port_write;       // mm_interconnect_0:spi_sdcard_spi_control_port_write -> spi_sdcard:write_n
	wire         mm_interconnect_0_spi_sdcard_spi_control_port_read;        // mm_interconnect_0:spi_sdcard_spi_control_port_read -> spi_sdcard:read_n
	wire  [15:0] mm_interconnect_0_spi_sdcard_spi_control_port_readdata;    // spi_sdcard:data_to_cpu -> mm_interconnect_0:spi_sdcard_spi_control_port_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex2_s1_writedata;               // mm_interconnect_0:pio_out_hex2_s1_writedata -> pio_out_hex2:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex2_s1_address;                 // mm_interconnect_0:pio_out_hex2_s1_address -> pio_out_hex2:address
	wire         mm_interconnect_0_pio_out_hex2_s1_chipselect;              // mm_interconnect_0:pio_out_hex2_s1_chipselect -> pio_out_hex2:chipselect
	wire         mm_interconnect_0_pio_out_hex2_s1_write;                   // mm_interconnect_0:pio_out_hex2_s1_write -> pio_out_hex2:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex2_s1_readdata;                // pio_out_hex2:readdata -> mm_interconnect_0:pio_out_hex2_s1_readdata
	wire  [31:0] mm_interconnect_0_pio_out_hex7_s1_writedata;               // mm_interconnect_0:pio_out_hex7_s1_writedata -> pio_out_hex7:writedata
	wire   [1:0] mm_interconnect_0_pio_out_hex7_s1_address;                 // mm_interconnect_0:pio_out_hex7_s1_address -> pio_out_hex7:address
	wire         mm_interconnect_0_pio_out_hex7_s1_chipselect;              // mm_interconnect_0:pio_out_hex7_s1_chipselect -> pio_out_hex7:chipselect
	wire         mm_interconnect_0_pio_out_hex7_s1_write;                   // mm_interconnect_0:pio_out_hex7_s1_write -> pio_out_hex7:write_n
	wire  [31:0] mm_interconnect_0_pio_out_hex7_s1_readdata;                // pio_out_hex7:readdata -> mm_interconnect_0:pio_out_hex7_s1_readdata
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_writedata;              // mm_interconnect_0:onchip_memory_s1_writedata -> onchip_memory:writedata
	wire  [15:0] mm_interconnect_0_onchip_memory_s1_address;                // mm_interconnect_0:onchip_memory_s1_address -> onchip_memory:address
	wire         mm_interconnect_0_onchip_memory_s1_chipselect;             // mm_interconnect_0:onchip_memory_s1_chipselect -> onchip_memory:chipselect
	wire         mm_interconnect_0_onchip_memory_s1_clken;                  // mm_interconnect_0:onchip_memory_s1_clken -> onchip_memory:clken
	wire         mm_interconnect_0_onchip_memory_s1_write;                  // mm_interconnect_0:onchip_memory_s1_write -> onchip_memory:write
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_readdata;               // onchip_memory:readdata -> mm_interconnect_0:onchip_memory_s1_readdata
	wire   [3:0] mm_interconnect_0_onchip_memory_s1_byteenable;             // mm_interconnect_0:onchip_memory_s1_byteenable -> onchip_memory:byteenable
	wire  [31:0] mm_interconnect_0_pio_out_ledr_flag_s1_writedata;          // mm_interconnect_0:pio_out_ledr_flag_s1_writedata -> pio_out_ledr_flag:writedata
	wire   [1:0] mm_interconnect_0_pio_out_ledr_flag_s1_address;            // mm_interconnect_0:pio_out_ledr_flag_s1_address -> pio_out_ledr_flag:address
	wire         mm_interconnect_0_pio_out_ledr_flag_s1_chipselect;         // mm_interconnect_0:pio_out_ledr_flag_s1_chipselect -> pio_out_ledr_flag:chipselect
	wire         mm_interconnect_0_pio_out_ledr_flag_s1_write;              // mm_interconnect_0:pio_out_ledr_flag_s1_write -> pio_out_ledr_flag:write_n
	wire  [31:0] mm_interconnect_0_pio_out_ledr_flag_s1_readdata;           // pio_out_ledr_flag:readdata -> mm_interconnect_0:pio_out_ledr_flag_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_in_key_s1_address;                   // mm_interconnect_0:pio_in_key_s1_address -> pio_in_key:address
	wire  [31:0] mm_interconnect_0_pio_in_key_s1_readdata;                  // pio_in_key:readdata -> mm_interconnect_0:pio_in_key_s1_readdata
	wire  [15:0] mm_interconnect_0_timer_s1_writedata;                      // mm_interconnect_0:timer_s1_writedata -> timer:writedata
	wire   [2:0] mm_interconnect_0_timer_s1_address;                        // mm_interconnect_0:timer_s1_address -> timer:address
	wire         mm_interconnect_0_timer_s1_chipselect;                     // mm_interconnect_0:timer_s1_chipselect -> timer:chipselect
	wire         mm_interconnect_0_timer_s1_write;                          // mm_interconnect_0:timer_s1_write -> timer:write_n
	wire  [15:0] mm_interconnect_0_timer_s1_readdata;                       // timer:readdata -> mm_interconnect_0:timer_s1_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_waitrequest;       // cpu:jtag_debug_module_waitrequest -> mm_interconnect_0:cpu_jtag_debug_module_waitrequest
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_writedata;         // mm_interconnect_0:cpu_jtag_debug_module_writedata -> cpu:jtag_debug_module_writedata
	wire   [8:0] mm_interconnect_0_cpu_jtag_debug_module_address;           // mm_interconnect_0:cpu_jtag_debug_module_address -> cpu:jtag_debug_module_address
	wire         mm_interconnect_0_cpu_jtag_debug_module_write;             // mm_interconnect_0:cpu_jtag_debug_module_write -> cpu:jtag_debug_module_write
	wire         mm_interconnect_0_cpu_jtag_debug_module_read;              // mm_interconnect_0:cpu_jtag_debug_module_read -> cpu:jtag_debug_module_read
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_readdata;          // cpu:jtag_debug_module_readdata -> mm_interconnect_0:cpu_jtag_debug_module_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_debugaccess;       // mm_interconnect_0:cpu_jtag_debug_module_debugaccess -> cpu:jtag_debug_module_debugaccess
	wire   [3:0] mm_interconnect_0_cpu_jtag_debug_module_byteenable;        // mm_interconnect_0:cpu_jtag_debug_module_byteenable -> cpu:jtag_debug_module_byteenable
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> jtag_uart:av_write_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> jtag_uart:av_read_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	wire  [31:0] mm_interconnect_0_pio_out_eep_sda_out_s1_writedata;        // mm_interconnect_0:pio_out_eep_sda_out_s1_writedata -> pio_out_eep_sda_out:writedata
	wire   [1:0] mm_interconnect_0_pio_out_eep_sda_out_s1_address;          // mm_interconnect_0:pio_out_eep_sda_out_s1_address -> pio_out_eep_sda_out:address
	wire         mm_interconnect_0_pio_out_eep_sda_out_s1_chipselect;       // mm_interconnect_0:pio_out_eep_sda_out_s1_chipselect -> pio_out_eep_sda_out:chipselect
	wire         mm_interconnect_0_pio_out_eep_sda_out_s1_write;            // mm_interconnect_0:pio_out_eep_sda_out_s1_write -> pio_out_eep_sda_out:write_n
	wire  [31:0] mm_interconnect_0_pio_out_eep_sda_out_s1_readdata;         // pio_out_eep_sda_out:readdata -> mm_interconnect_0:pio_out_eep_sda_out_s1_readdata
	wire         irq_mapper_receiver0_irq;                                  // jtag_uart:av_irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                  // spi_sdcard:irq -> irq_mapper:receiver1_irq
	wire         irq_mapper_receiver2_irq;                                  // timer:irq -> irq_mapper:receiver2_irq
	wire  [31:0] cpu_d_irq_irq;                                             // irq_mapper:sender_irq -> cpu:d_irq
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [cpu:reset_n, irq_mapper:reset, jtag_uart:rst_n, mm_interconnect_0:cpu_reset_n_reset_bridge_in_reset_reset, onchip_memory:reset, pio_in_eep_sda_in:reset_n, pio_in_key:reset_n, pio_in_keyboard_data:reset_n, pio_in_keyboard_status:reset_n, pio_in_sw:reset_n, pio_out_eep_scl:reset_n, pio_out_eep_sda_oe:reset_n, pio_out_eep_sda_out:reset_n, pio_out_hex0:reset_n, pio_out_hex1:reset_n, pio_out_hex2:reset_n, pio_out_hex3:reset_n, pio_out_hex4:reset_n, pio_out_hex5:reset_n, pio_out_hex6:reset_n, pio_out_hex7:reset_n, pio_out_keyboard_ack:reset_n, pio_out_lcd_ctrl:reset_n, pio_out_lcd_data:reset_n, pio_out_ledg8:reset_n, pio_out_ledg:reset_n, pio_out_ledr:reset_n, pio_out_ledr_flag:reset_n, rst_translator:in_reset, spi_sdcard:reset_n, sysid_qsys:reset_n, timer:reset_n]
	wire         rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [cpu:reset_req, onchip_memory:reset_req, rst_translator:reset_req_in]

	nios_cpu cpu (
		.clk                                   (clk_clk),                                             //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                     //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                  //                          .reset_req
		.d_address                             (cpu_data_master_address),                             //               data_master.address
		.d_byteenable                          (cpu_data_master_byteenable),                          //                          .byteenable
		.d_read                                (cpu_data_master_read),                                //                          .read
		.d_readdata                            (cpu_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (cpu_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (cpu_data_master_write),                               //                          .write
		.d_writedata                           (cpu_data_master_writedata),                           //                          .writedata
		.jtag_debug_module_debugaccess_to_roms (cpu_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (cpu_instruction_master_address),                      //        instruction_master.address
		.i_read                                (cpu_instruction_master_read),                         //                          .read
		.i_readdata                            (cpu_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (cpu_instruction_master_waitrequest),                  //                          .waitrequest
		.d_irq                                 (cpu_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (),                                                    //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_cpu_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_cpu_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_cpu_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_cpu_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_cpu_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_cpu_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_cpu_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_cpu_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                     // custom_instruction_master.readra
	);

	nios_onchip_memory onchip_memory (
		.clk        (clk_clk),                                       //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)             //       .reset_req
	);

	nios_jtag_uart jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	nios_sysid_qsys sysid_qsys (
		.clock    (clk_clk),                                             //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                     //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_control_slave_address)   //              .address
	);

	nios_pio_in_sw pio_in_sw (
		.clk      (clk_clk),                                 //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pio_in_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_in_sw_s1_readdata), //                    .readdata
		.in_port  (pio_in_sw_external_connection_export)     // external_connection.export
	);

	nios_pio_in_key pio_in_key (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_pio_in_key_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_in_key_s1_readdata), //                    .readdata
		.in_port  (pio_in_key_external_connection_export)     // external_connection.export
	);

	nios_pio_out_ledr pio_out_ledr (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_ledr_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_ledr_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_ledr_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_ledr_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_ledr_s1_readdata),   //                    .readdata
		.out_port   (pio_out_ledr_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_ledg (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_ledg_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_ledg_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_ledg_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_ledg_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_ledg_s1_readdata),   //                    .readdata
		.out_port   (pio_out_ledg_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg8 pio_out_ledg8 (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_ledg8_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_ledg8_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_ledg8_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_ledg8_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_ledg8_s1_readdata),   //                    .readdata
		.out_port   (pio_out_ledg8_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex0 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex0_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex0_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex1 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex1_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex1_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex2 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex2_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex2_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex3 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex3_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex3_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex4 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex4_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex4_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex5 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex5_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex5_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex5_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex5_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex5_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex5_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex6 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex6_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex6_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex6_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex6_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex6_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex6_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_hex7 (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_hex7_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_hex7_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_hex7_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_hex7_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_hex7_s1_readdata),   //                    .readdata
		.out_port   (pio_out_hex7_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg pio_out_lcd_data (
		.clk        (clk_clk),                                          //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                  //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_lcd_data_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_lcd_data_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_lcd_data_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_lcd_data_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_lcd_data_s1_readdata),   //                    .readdata
		.out_port   (pio_out_lcd_data_external_connection_export)       // external_connection.export
	);

	nios_pio_out_lcd_ctrl pio_out_lcd_ctrl (
		.clk        (clk_clk),                                          //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                  //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_lcd_ctrl_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_lcd_ctrl_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_lcd_ctrl_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_lcd_ctrl_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_lcd_ctrl_s1_readdata),   //                    .readdata
		.out_port   (pio_out_lcd_ctrl_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg8 pio_out_eep_scl (
		.clk        (clk_clk),                                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_eep_scl_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_eep_scl_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_eep_scl_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_eep_scl_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_eep_scl_s1_readdata),   //                    .readdata
		.out_port   (pio_out_eep_scl_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg8 pio_out_eep_sda_out (
		.clk        (clk_clk),                                             //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                     //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_eep_sda_out_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_eep_sda_out_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_eep_sda_out_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_eep_sda_out_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_eep_sda_out_s1_readdata),   //                    .readdata
		.out_port   (pio_out_eep_sda_out_external_connection_export)       // external_connection.export
	);

	nios_pio_out_ledg8 pio_out_eep_sda_oe (
		.clk        (clk_clk),                                            //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                    //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_eep_sda_oe_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_eep_sda_oe_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_eep_sda_oe_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_eep_sda_oe_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_eep_sda_oe_s1_readdata),   //                    .readdata
		.out_port   (pio_out_eep_sda_oe_external_connection_export)       // external_connection.export
	);

	nios_pio_in_eep_sda_in pio_in_eep_sda_in (
		.clk      (clk_clk),                                         //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                 //               reset.reset_n
		.address  (mm_interconnect_0_pio_in_eep_sda_in_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_in_eep_sda_in_s1_readdata), //                    .readdata
		.in_port  (pio_in_eep_sda_in_external_connection_export)     // external_connection.export
	);

	nios_pio_in_keyboard_data pio_in_keyboard_data (
		.clk      (clk_clk),                                            //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                    //               reset.reset_n
		.address  (mm_interconnect_0_pio_in_keyboard_data_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_in_keyboard_data_s1_readdata), //                    .readdata
		.in_port  (pio_in_keyboard_data_external_connection_export)     // external_connection.export
	);

	nios_pio_in_keyboard_data pio_in_keyboard_status (
		.clk      (clk_clk),                                              //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                      //               reset.reset_n
		.address  (mm_interconnect_0_pio_in_keyboard_status_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_in_keyboard_status_s1_readdata), //                    .readdata
		.in_port  (pio_in_keyboard_status_external_connection_export)     // external_connection.export
	);

	nios_pio_out_ledg8 pio_out_keyboard_ack (
		.clk        (clk_clk),                                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                      //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_keyboard_ack_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_keyboard_ack_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_keyboard_ack_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_keyboard_ack_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_keyboard_ack_s1_readdata),   //                    .readdata
		.out_port   (pio_out_keyboard_ack_external_connection_export)       // external_connection.export
	);

	nios_spi_sdcard spi_sdcard (
		.clk           (clk_clk),                                                  //              clk.clk
		.reset_n       (~rst_controller_reset_out_reset),                          //            reset.reset_n
		.data_from_cpu (mm_interconnect_0_spi_sdcard_spi_control_port_writedata),  // spi_control_port.writedata
		.data_to_cpu   (mm_interconnect_0_spi_sdcard_spi_control_port_readdata),   //                 .readdata
		.mem_addr      (mm_interconnect_0_spi_sdcard_spi_control_port_address),    //                 .address
		.read_n        (~mm_interconnect_0_spi_sdcard_spi_control_port_read),      //                 .read_n
		.spi_select    (mm_interconnect_0_spi_sdcard_spi_control_port_chipselect), //                 .chipselect
		.write_n       (~mm_interconnect_0_spi_sdcard_spi_control_port_write),     //                 .write_n
		.irq           (irq_mapper_receiver1_irq),                                 //              irq.irq
		.MISO          (spi_sdcard_external_MISO),                                 //         external.export
		.MOSI          (spi_sdcard_external_MOSI),                                 //                 .export
		.SCLK          (spi_sdcard_external_SCLK),                                 //                 .export
		.SS_n          (spi_sdcard_external_SS_n)                                  //                 .export
	);

	nios_pio_out_ledg pio_out_ledr_flag (
		.clk        (clk_clk),                                           //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                   //               reset.reset_n
		.address    (mm_interconnect_0_pio_out_ledr_flag_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_out_ledr_flag_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_out_ledr_flag_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_out_ledr_flag_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_out_ledr_flag_s1_readdata),   //                    .readdata
		.out_port   (pio_out_ledr_flag_external_connection_export)       // external_connection.export
	);

	nios_timer timer (
		.clk        (clk_clk),                               //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       // reset.reset_n
		.address    (mm_interconnect_0_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver2_irq)               //   irq.irq
	);

	nios_mm_interconnect_0 mm_interconnect_0 (
		.clk_clk_clk                             (clk_clk),                                                   //                           clk_clk.clk
		.cpu_reset_n_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // cpu_reset_n_reset_bridge_in_reset.reset
		.cpu_data_master_address                 (cpu_data_master_address),                                   //                   cpu_data_master.address
		.cpu_data_master_waitrequest             (cpu_data_master_waitrequest),                               //                                  .waitrequest
		.cpu_data_master_byteenable              (cpu_data_master_byteenable),                                //                                  .byteenable
		.cpu_data_master_read                    (cpu_data_master_read),                                      //                                  .read
		.cpu_data_master_readdata                (cpu_data_master_readdata),                                  //                                  .readdata
		.cpu_data_master_write                   (cpu_data_master_write),                                     //                                  .write
		.cpu_data_master_writedata               (cpu_data_master_writedata),                                 //                                  .writedata
		.cpu_data_master_debugaccess             (cpu_data_master_debugaccess),                               //                                  .debugaccess
		.cpu_instruction_master_address          (cpu_instruction_master_address),                            //            cpu_instruction_master.address
		.cpu_instruction_master_waitrequest      (cpu_instruction_master_waitrequest),                        //                                  .waitrequest
		.cpu_instruction_master_read             (cpu_instruction_master_read),                               //                                  .read
		.cpu_instruction_master_readdata         (cpu_instruction_master_readdata),                           //                                  .readdata
		.cpu_jtag_debug_module_address           (mm_interconnect_0_cpu_jtag_debug_module_address),           //             cpu_jtag_debug_module.address
		.cpu_jtag_debug_module_write             (mm_interconnect_0_cpu_jtag_debug_module_write),             //                                  .write
		.cpu_jtag_debug_module_read              (mm_interconnect_0_cpu_jtag_debug_module_read),              //                                  .read
		.cpu_jtag_debug_module_readdata          (mm_interconnect_0_cpu_jtag_debug_module_readdata),          //                                  .readdata
		.cpu_jtag_debug_module_writedata         (mm_interconnect_0_cpu_jtag_debug_module_writedata),         //                                  .writedata
		.cpu_jtag_debug_module_byteenable        (mm_interconnect_0_cpu_jtag_debug_module_byteenable),        //                                  .byteenable
		.cpu_jtag_debug_module_waitrequest       (mm_interconnect_0_cpu_jtag_debug_module_waitrequest),       //                                  .waitrequest
		.cpu_jtag_debug_module_debugaccess       (mm_interconnect_0_cpu_jtag_debug_module_debugaccess),       //                                  .debugaccess
		.jtag_uart_avalon_jtag_slave_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //       jtag_uart_avalon_jtag_slave.address
		.jtag_uart_avalon_jtag_slave_write       (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                  .write
		.jtag_uart_avalon_jtag_slave_read        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                  .read
		.jtag_uart_avalon_jtag_slave_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                  .readdata
		.jtag_uart_avalon_jtag_slave_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                  .writedata
		.jtag_uart_avalon_jtag_slave_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                  .waitrequest
		.jtag_uart_avalon_jtag_slave_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                  .chipselect
		.onchip_memory_s1_address                (mm_interconnect_0_onchip_memory_s1_address),                //                  onchip_memory_s1.address
		.onchip_memory_s1_write                  (mm_interconnect_0_onchip_memory_s1_write),                  //                                  .write
		.onchip_memory_s1_readdata               (mm_interconnect_0_onchip_memory_s1_readdata),               //                                  .readdata
		.onchip_memory_s1_writedata              (mm_interconnect_0_onchip_memory_s1_writedata),              //                                  .writedata
		.onchip_memory_s1_byteenable             (mm_interconnect_0_onchip_memory_s1_byteenable),             //                                  .byteenable
		.onchip_memory_s1_chipselect             (mm_interconnect_0_onchip_memory_s1_chipselect),             //                                  .chipselect
		.onchip_memory_s1_clken                  (mm_interconnect_0_onchip_memory_s1_clken),                  //                                  .clken
		.pio_in_eep_sda_in_s1_address            (mm_interconnect_0_pio_in_eep_sda_in_s1_address),            //              pio_in_eep_sda_in_s1.address
		.pio_in_eep_sda_in_s1_readdata           (mm_interconnect_0_pio_in_eep_sda_in_s1_readdata),           //                                  .readdata
		.pio_in_key_s1_address                   (mm_interconnect_0_pio_in_key_s1_address),                   //                     pio_in_key_s1.address
		.pio_in_key_s1_readdata                  (mm_interconnect_0_pio_in_key_s1_readdata),                  //                                  .readdata
		.pio_in_keyboard_data_s1_address         (mm_interconnect_0_pio_in_keyboard_data_s1_address),         //           pio_in_keyboard_data_s1.address
		.pio_in_keyboard_data_s1_readdata        (mm_interconnect_0_pio_in_keyboard_data_s1_readdata),        //                                  .readdata
		.pio_in_keyboard_status_s1_address       (mm_interconnect_0_pio_in_keyboard_status_s1_address),       //         pio_in_keyboard_status_s1.address
		.pio_in_keyboard_status_s1_readdata      (mm_interconnect_0_pio_in_keyboard_status_s1_readdata),      //                                  .readdata
		.pio_in_sw_s1_address                    (mm_interconnect_0_pio_in_sw_s1_address),                    //                      pio_in_sw_s1.address
		.pio_in_sw_s1_readdata                   (mm_interconnect_0_pio_in_sw_s1_readdata),                   //                                  .readdata
		.pio_out_eep_scl_s1_address              (mm_interconnect_0_pio_out_eep_scl_s1_address),              //                pio_out_eep_scl_s1.address
		.pio_out_eep_scl_s1_write                (mm_interconnect_0_pio_out_eep_scl_s1_write),                //                                  .write
		.pio_out_eep_scl_s1_readdata             (mm_interconnect_0_pio_out_eep_scl_s1_readdata),             //                                  .readdata
		.pio_out_eep_scl_s1_writedata            (mm_interconnect_0_pio_out_eep_scl_s1_writedata),            //                                  .writedata
		.pio_out_eep_scl_s1_chipselect           (mm_interconnect_0_pio_out_eep_scl_s1_chipselect),           //                                  .chipselect
		.pio_out_eep_sda_oe_s1_address           (mm_interconnect_0_pio_out_eep_sda_oe_s1_address),           //             pio_out_eep_sda_oe_s1.address
		.pio_out_eep_sda_oe_s1_write             (mm_interconnect_0_pio_out_eep_sda_oe_s1_write),             //                                  .write
		.pio_out_eep_sda_oe_s1_readdata          (mm_interconnect_0_pio_out_eep_sda_oe_s1_readdata),          //                                  .readdata
		.pio_out_eep_sda_oe_s1_writedata         (mm_interconnect_0_pio_out_eep_sda_oe_s1_writedata),         //                                  .writedata
		.pio_out_eep_sda_oe_s1_chipselect        (mm_interconnect_0_pio_out_eep_sda_oe_s1_chipselect),        //                                  .chipselect
		.pio_out_eep_sda_out_s1_address          (mm_interconnect_0_pio_out_eep_sda_out_s1_address),          //            pio_out_eep_sda_out_s1.address
		.pio_out_eep_sda_out_s1_write            (mm_interconnect_0_pio_out_eep_sda_out_s1_write),            //                                  .write
		.pio_out_eep_sda_out_s1_readdata         (mm_interconnect_0_pio_out_eep_sda_out_s1_readdata),         //                                  .readdata
		.pio_out_eep_sda_out_s1_writedata        (mm_interconnect_0_pio_out_eep_sda_out_s1_writedata),        //                                  .writedata
		.pio_out_eep_sda_out_s1_chipselect       (mm_interconnect_0_pio_out_eep_sda_out_s1_chipselect),       //                                  .chipselect
		.pio_out_hex0_s1_address                 (mm_interconnect_0_pio_out_hex0_s1_address),                 //                   pio_out_hex0_s1.address
		.pio_out_hex0_s1_write                   (mm_interconnect_0_pio_out_hex0_s1_write),                   //                                  .write
		.pio_out_hex0_s1_readdata                (mm_interconnect_0_pio_out_hex0_s1_readdata),                //                                  .readdata
		.pio_out_hex0_s1_writedata               (mm_interconnect_0_pio_out_hex0_s1_writedata),               //                                  .writedata
		.pio_out_hex0_s1_chipselect              (mm_interconnect_0_pio_out_hex0_s1_chipselect),              //                                  .chipselect
		.pio_out_hex1_s1_address                 (mm_interconnect_0_pio_out_hex1_s1_address),                 //                   pio_out_hex1_s1.address
		.pio_out_hex1_s1_write                   (mm_interconnect_0_pio_out_hex1_s1_write),                   //                                  .write
		.pio_out_hex1_s1_readdata                (mm_interconnect_0_pio_out_hex1_s1_readdata),                //                                  .readdata
		.pio_out_hex1_s1_writedata               (mm_interconnect_0_pio_out_hex1_s1_writedata),               //                                  .writedata
		.pio_out_hex1_s1_chipselect              (mm_interconnect_0_pio_out_hex1_s1_chipselect),              //                                  .chipselect
		.pio_out_hex2_s1_address                 (mm_interconnect_0_pio_out_hex2_s1_address),                 //                   pio_out_hex2_s1.address
		.pio_out_hex2_s1_write                   (mm_interconnect_0_pio_out_hex2_s1_write),                   //                                  .write
		.pio_out_hex2_s1_readdata                (mm_interconnect_0_pio_out_hex2_s1_readdata),                //                                  .readdata
		.pio_out_hex2_s1_writedata               (mm_interconnect_0_pio_out_hex2_s1_writedata),               //                                  .writedata
		.pio_out_hex2_s1_chipselect              (mm_interconnect_0_pio_out_hex2_s1_chipselect),              //                                  .chipselect
		.pio_out_hex3_s1_address                 (mm_interconnect_0_pio_out_hex3_s1_address),                 //                   pio_out_hex3_s1.address
		.pio_out_hex3_s1_write                   (mm_interconnect_0_pio_out_hex3_s1_write),                   //                                  .write
		.pio_out_hex3_s1_readdata                (mm_interconnect_0_pio_out_hex3_s1_readdata),                //                                  .readdata
		.pio_out_hex3_s1_writedata               (mm_interconnect_0_pio_out_hex3_s1_writedata),               //                                  .writedata
		.pio_out_hex3_s1_chipselect              (mm_interconnect_0_pio_out_hex3_s1_chipselect),              //                                  .chipselect
		.pio_out_hex4_s1_address                 (mm_interconnect_0_pio_out_hex4_s1_address),                 //                   pio_out_hex4_s1.address
		.pio_out_hex4_s1_write                   (mm_interconnect_0_pio_out_hex4_s1_write),                   //                                  .write
		.pio_out_hex4_s1_readdata                (mm_interconnect_0_pio_out_hex4_s1_readdata),                //                                  .readdata
		.pio_out_hex4_s1_writedata               (mm_interconnect_0_pio_out_hex4_s1_writedata),               //                                  .writedata
		.pio_out_hex4_s1_chipselect              (mm_interconnect_0_pio_out_hex4_s1_chipselect),              //                                  .chipselect
		.pio_out_hex5_s1_address                 (mm_interconnect_0_pio_out_hex5_s1_address),                 //                   pio_out_hex5_s1.address
		.pio_out_hex5_s1_write                   (mm_interconnect_0_pio_out_hex5_s1_write),                   //                                  .write
		.pio_out_hex5_s1_readdata                (mm_interconnect_0_pio_out_hex5_s1_readdata),                //                                  .readdata
		.pio_out_hex5_s1_writedata               (mm_interconnect_0_pio_out_hex5_s1_writedata),               //                                  .writedata
		.pio_out_hex5_s1_chipselect              (mm_interconnect_0_pio_out_hex5_s1_chipselect),              //                                  .chipselect
		.pio_out_hex6_s1_address                 (mm_interconnect_0_pio_out_hex6_s1_address),                 //                   pio_out_hex6_s1.address
		.pio_out_hex6_s1_write                   (mm_interconnect_0_pio_out_hex6_s1_write),                   //                                  .write
		.pio_out_hex6_s1_readdata                (mm_interconnect_0_pio_out_hex6_s1_readdata),                //                                  .readdata
		.pio_out_hex6_s1_writedata               (mm_interconnect_0_pio_out_hex6_s1_writedata),               //                                  .writedata
		.pio_out_hex6_s1_chipselect              (mm_interconnect_0_pio_out_hex6_s1_chipselect),              //                                  .chipselect
		.pio_out_hex7_s1_address                 (mm_interconnect_0_pio_out_hex7_s1_address),                 //                   pio_out_hex7_s1.address
		.pio_out_hex7_s1_write                   (mm_interconnect_0_pio_out_hex7_s1_write),                   //                                  .write
		.pio_out_hex7_s1_readdata                (mm_interconnect_0_pio_out_hex7_s1_readdata),                //                                  .readdata
		.pio_out_hex7_s1_writedata               (mm_interconnect_0_pio_out_hex7_s1_writedata),               //                                  .writedata
		.pio_out_hex7_s1_chipselect              (mm_interconnect_0_pio_out_hex7_s1_chipselect),              //                                  .chipselect
		.pio_out_keyboard_ack_s1_address         (mm_interconnect_0_pio_out_keyboard_ack_s1_address),         //           pio_out_keyboard_ack_s1.address
		.pio_out_keyboard_ack_s1_write           (mm_interconnect_0_pio_out_keyboard_ack_s1_write),           //                                  .write
		.pio_out_keyboard_ack_s1_readdata        (mm_interconnect_0_pio_out_keyboard_ack_s1_readdata),        //                                  .readdata
		.pio_out_keyboard_ack_s1_writedata       (mm_interconnect_0_pio_out_keyboard_ack_s1_writedata),       //                                  .writedata
		.pio_out_keyboard_ack_s1_chipselect      (mm_interconnect_0_pio_out_keyboard_ack_s1_chipselect),      //                                  .chipselect
		.pio_out_lcd_ctrl_s1_address             (mm_interconnect_0_pio_out_lcd_ctrl_s1_address),             //               pio_out_lcd_ctrl_s1.address
		.pio_out_lcd_ctrl_s1_write               (mm_interconnect_0_pio_out_lcd_ctrl_s1_write),               //                                  .write
		.pio_out_lcd_ctrl_s1_readdata            (mm_interconnect_0_pio_out_lcd_ctrl_s1_readdata),            //                                  .readdata
		.pio_out_lcd_ctrl_s1_writedata           (mm_interconnect_0_pio_out_lcd_ctrl_s1_writedata),           //                                  .writedata
		.pio_out_lcd_ctrl_s1_chipselect          (mm_interconnect_0_pio_out_lcd_ctrl_s1_chipselect),          //                                  .chipselect
		.pio_out_lcd_data_s1_address             (mm_interconnect_0_pio_out_lcd_data_s1_address),             //               pio_out_lcd_data_s1.address
		.pio_out_lcd_data_s1_write               (mm_interconnect_0_pio_out_lcd_data_s1_write),               //                                  .write
		.pio_out_lcd_data_s1_readdata            (mm_interconnect_0_pio_out_lcd_data_s1_readdata),            //                                  .readdata
		.pio_out_lcd_data_s1_writedata           (mm_interconnect_0_pio_out_lcd_data_s1_writedata),           //                                  .writedata
		.pio_out_lcd_data_s1_chipselect          (mm_interconnect_0_pio_out_lcd_data_s1_chipselect),          //                                  .chipselect
		.pio_out_ledg_s1_address                 (mm_interconnect_0_pio_out_ledg_s1_address),                 //                   pio_out_ledg_s1.address
		.pio_out_ledg_s1_write                   (mm_interconnect_0_pio_out_ledg_s1_write),                   //                                  .write
		.pio_out_ledg_s1_readdata                (mm_interconnect_0_pio_out_ledg_s1_readdata),                //                                  .readdata
		.pio_out_ledg_s1_writedata               (mm_interconnect_0_pio_out_ledg_s1_writedata),               //                                  .writedata
		.pio_out_ledg_s1_chipselect              (mm_interconnect_0_pio_out_ledg_s1_chipselect),              //                                  .chipselect
		.pio_out_ledg8_s1_address                (mm_interconnect_0_pio_out_ledg8_s1_address),                //                  pio_out_ledg8_s1.address
		.pio_out_ledg8_s1_write                  (mm_interconnect_0_pio_out_ledg8_s1_write),                  //                                  .write
		.pio_out_ledg8_s1_readdata               (mm_interconnect_0_pio_out_ledg8_s1_readdata),               //                                  .readdata
		.pio_out_ledg8_s1_writedata              (mm_interconnect_0_pio_out_ledg8_s1_writedata),              //                                  .writedata
		.pio_out_ledg8_s1_chipselect             (mm_interconnect_0_pio_out_ledg8_s1_chipselect),             //                                  .chipselect
		.pio_out_ledr_s1_address                 (mm_interconnect_0_pio_out_ledr_s1_address),                 //                   pio_out_ledr_s1.address
		.pio_out_ledr_s1_write                   (mm_interconnect_0_pio_out_ledr_s1_write),                   //                                  .write
		.pio_out_ledr_s1_readdata                (mm_interconnect_0_pio_out_ledr_s1_readdata),                //                                  .readdata
		.pio_out_ledr_s1_writedata               (mm_interconnect_0_pio_out_ledr_s1_writedata),               //                                  .writedata
		.pio_out_ledr_s1_chipselect              (mm_interconnect_0_pio_out_ledr_s1_chipselect),              //                                  .chipselect
		.pio_out_ledr_flag_s1_address            (mm_interconnect_0_pio_out_ledr_flag_s1_address),            //              pio_out_ledr_flag_s1.address
		.pio_out_ledr_flag_s1_write              (mm_interconnect_0_pio_out_ledr_flag_s1_write),              //                                  .write
		.pio_out_ledr_flag_s1_readdata           (mm_interconnect_0_pio_out_ledr_flag_s1_readdata),           //                                  .readdata
		.pio_out_ledr_flag_s1_writedata          (mm_interconnect_0_pio_out_ledr_flag_s1_writedata),          //                                  .writedata
		.pio_out_ledr_flag_s1_chipselect         (mm_interconnect_0_pio_out_ledr_flag_s1_chipselect),         //                                  .chipselect
		.spi_sdcard_spi_control_port_address     (mm_interconnect_0_spi_sdcard_spi_control_port_address),     //       spi_sdcard_spi_control_port.address
		.spi_sdcard_spi_control_port_write       (mm_interconnect_0_spi_sdcard_spi_control_port_write),       //                                  .write
		.spi_sdcard_spi_control_port_read        (mm_interconnect_0_spi_sdcard_spi_control_port_read),        //                                  .read
		.spi_sdcard_spi_control_port_readdata    (mm_interconnect_0_spi_sdcard_spi_control_port_readdata),    //                                  .readdata
		.spi_sdcard_spi_control_port_writedata   (mm_interconnect_0_spi_sdcard_spi_control_port_writedata),   //                                  .writedata
		.spi_sdcard_spi_control_port_chipselect  (mm_interconnect_0_spi_sdcard_spi_control_port_chipselect),  //                                  .chipselect
		.sysid_qsys_control_slave_address        (mm_interconnect_0_sysid_qsys_control_slave_address),        //          sysid_qsys_control_slave.address
		.sysid_qsys_control_slave_readdata       (mm_interconnect_0_sysid_qsys_control_slave_readdata),       //                                  .readdata
		.timer_s1_address                        (mm_interconnect_0_timer_s1_address),                        //                          timer_s1.address
		.timer_s1_write                          (mm_interconnect_0_timer_s1_write),                          //                                  .write
		.timer_s1_readdata                       (mm_interconnect_0_timer_s1_readdata),                       //                                  .readdata
		.timer_s1_writedata                      (mm_interconnect_0_timer_s1_writedata),                      //                                  .writedata
		.timer_s1_chipselect                     (mm_interconnect_0_timer_s1_chipselect)                      //                                  .chipselect
	);

	nios_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),       // receiver2.irq
		.sender_irq    (cpu_d_irq_irq)                   //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
